# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorPaletteExtractor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ColorPaletteExtractor

  target 'ColorPaletteExtractorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ColorPaletteExtractorUITests' do
    # Pods for testing
  end

pod 'Alamofire'

end
